extends RefCounted

## Frozen vocabulary for the whole project. Enums and simulation constants.
##
## MANAGER-OWNED. Do not edit this file. If you need a value added, propose the
## exact line in TEAM_LOG.md and the manager applies it immediately.
##
## NOTHING IN THIS PROJECT USES `class_name`. Every script that needs another
## one preloads it into a const with the same name:
##
##     const CG := preload("res://Scripts/Core/CG.gd")
##
## and then reads exactly as if it were a global class: `CG.Team.PLAYER`, type
## annotations, typed arrays, exported fields, `is` checks. All of that was
## measured working on 2026-08-12.
##
## The reason is not style. `class_name` identifiers do not resolve outside the
## Godot editor: they are registered by the editor's filesystem scan, and on
## this machine the headless editor never completes one. Every mode was tried,
## on both the Steam build and the official 4.7.1 build, and every one hung with
## no output. Hand-writing .godot/global_script_class_cache.cfg does not fix it
## either; the entries load and resolution still fails.
##
## So a project built on `class_name` here has no gate at all, which is a worse
## trade than one preload line per dependency. A session that adds `class_name`
## will find the gate cannot parse its file, and the error will name a type
## rather than the cause. That is what this paragraph is for.
##
## It buys one real thing back: with no global namespace, two sessions cannot
## collide on a name.
##
## Everything the simulation measures is in ticks and world units. There are no
## seconds and no delta times below the presentation layer: a float delta makes
## the same fight play out differently on a different frame rate, and "re-run
## the same fight" is an acceptance criterion for this slice.

const TICKS_PER_SECOND := 30
const TICK_SECONDS := 1.0 / float(TICKS_PER_SECOND)

## Arena is centred on (0, 0). World units, not pixels. The view scales.
const ARENA_HALF_WIDTH := 480.0
const ARENA_HALF_HEIGHT := 270.0

## A fight that has not resolved by this tick is a draw. Stops a stalemate
## between two passive parties from hanging the runner.
const MAX_TICKS := TICKS_PER_SECOND * 120

enum Team {
	PLAYER,
	ENEMY,
}

enum Attribute {
	STR,
	DEX,
	AGI,
	CON,
	INT,
	ATN,
	WIS,
}

enum ResourceKind {
	MANA,
	RAGE,
	ENERGY,
}

enum DamageType {
	PHYSICAL,
	FIRE,
	WATER,
	AIR,
	EARTH,
	DIVINE,
	PROFANE,
	RAW,
}

enum Method { MARTIAL, MAGICAL }
enum Style { MELEE, RANGED, SUMMONER }
enum Role { DPS, SUPPORT, ANTI_SUPPORT, TANK, HEALER }

## Status effects. Each damage type has one helpful and one harmful effect in
## README.md; only the ones the slice actually applies are listed. Adding one is
## a manager edit, not a content edit, because the sim must handle it.
enum Status {
	SHIELD,
	BLEED,
	ENRAGE,
	BURN,
	HASTE,
	STUN,
	BLOCK,
	MARKED,
	POISON,
}

## What a decision layer asks a unit to do on a tick. The plan interpreter and
## the default behaviour both produce these; the simulation consumes them and is
## the only thing allowed to mutate a CombatUnit.
enum IntentKind {
	IDLE,
	MOVE_TO,
	USE_ACTION,
}

## Everything the simulation reports outwards. The view and the combat log read
## these and nothing else: no reaching into CombatUnit for "what just happened".
enum EventKind {
	FIGHT_START,
	FIGHT_END,
	DAMAGE,
	HEAL,
	DEATH,
	ACTION_START,
	ACTION_FIRE,
	STATUS_APPLIED,
	STATUS_EXPIRED,
	RESOURCE_SPENT,
}

static func attribute_name(a: Attribute) -> String:
	match a:
		Attribute.STR: return "STR"
		Attribute.DEX: return "DEX"
		Attribute.AGI: return "AGI"
		Attribute.CON: return "CON"
		Attribute.INT: return "INT"
		Attribute.ATN: return "ATN"
		Attribute.WIS: return "WIS"
	return "?"

static func damage_type_name(d: DamageType) -> String:
	match d:
		DamageType.PHYSICAL: return "Physical"
		DamageType.FIRE: return "Fire"
		DamageType.WATER: return "Water"
		DamageType.AIR: return "Air"
		DamageType.EARTH: return "Earth"
		DamageType.DIVINE: return "Divine"
		DamageType.PROFANE: return "Profane"
		DamageType.RAW: return "Raw"
	return "?"
