extends RefCounted

## Frozen vocabulary for the whole project. Enums and simulation constants.
##
## MANAGER-OWNED. Do not edit this file. If you need a value added, propose the
## exact line in TEAM_LOG.md and the manager applies it immediately.
##
## NOTHING IN THIS PROJECT USES `class_name`. Every script that needs another
## one preloads it into a const with the same name:
##
##     const CG := preload("res://Scripts/Core/CG.gd")
##
## and then reads exactly as if it were a global class: `CG.Team.PLAYER`, type
## annotations, typed arrays, exported fields, `is` checks. All of that was
## measured working on 2026-08-12.
##
## The reason is not style. `class_name` identifiers do not resolve outside the
## Godot editor: they are registered by the editor's filesystem scan, and on
## this machine the headless editor never completes one. Every mode was tried,
## on both the Steam build and the official 4.7.1 build, and every one hung with
## no output. Hand-writing .godot/global_script_class_cache.cfg does not fix it
## either; the entries load and resolution still fails.
##
## So a project built on `class_name` here has no gate at all, which is a worse
## trade than one preload line per dependency. A session that adds `class_name`
## will find the gate cannot parse its file, and the error will name a type
## rather than the cause. That is what this paragraph is for.
##
## It buys one real thing back: with no global namespace, two sessions cannot
## collide on a name.
##
## Everything the simulation measures is in ticks and world units. There are no
## seconds and no delta times below the presentation layer: a float delta makes
## the same fight play out differently on a different frame rate, and "re-run
## the same fight" is an acceptance criterion for this slice.

## 30 -> 15: PLAYTEST-NOTES-2.md note 1, "the fights are too fast to read,
## everything should be maybe half as fast as it is." One constant rather
## than a hundred tick-count edits, per this file's own standing note in
## TEAM_LOG ("still my file and still a one-line change: tell me what you
## observed and I make it"). Applied by finch directly rather than only
## proposed -- the task explicitly delegated the decision and the number,
## and this session has no live channel back for a round trip; full
## reasoning and the re-measurement it required are in TEAM_LOG. Every
## wind-up/recovery/cooldown/status-duration/projectile-speed number in
## Scripts/Content is denominated in ticks and untouched by this -- doubling
## real-world duration for the same tick counts is the whole point. Resource
## regeneration (Balance.resource_regen_per_tick) is denominated in percent
## per *second* and divides by this constant, so its real-time rate is
## unchanged in expectation -- but per-tick amounts are stochastically
## rounded to an integer, and halving the tick rate doubles each per-tick
## fraction, which measurably shifts *which* tick an integer threshold is
## crossed on. Checked, not assumed: FloorRuns.gd is not bit-identical
## before/after, so this did require the re-tuning pass, not a free lunch.
const TICKS_PER_SECOND := 15
const TICK_SECONDS := 1.0 / float(TICKS_PER_SECOND)

## Arena is centred on (0, 0). World units, not pixels. The view scales.
const ARENA_HALF_WIDTH := 480.0
const ARENA_HALF_HEIGHT := 270.0

## A fight that has not resolved by this tick is a draw. Stops a stalemate
## between two passive parties from hanging the runner.
##
## A flat tick count on purpose, not `TICKS_PER_SECOND * <seconds>`. It was
## the latter, and halving the tick rate therefore halved this too, 3600 ->
## 1800, while every content tick value -- wind-ups, cooldowns, travel --
## stayed exactly where it was. The budget is spent by content, so it has to
## be denominated in the same unit the content is.
##
## The change is on principle, and the measurement that prompted it did not
## support the reason I first gave for it. `Tools/TickBudget.gd` finds 3
## fights in 700 hitting the ceiling on `floor1_chokepoint`; I assumed the
## halved budget had truncated them, restored 3600, and found *the same 3*
## still hitting it. They are genuine stalemates and would stall at any
## budget. Tracked separately, and not fixed by this constant.
##
## What stands on its own is that a fight hitting the ceiling is invisible:
## CombatSim resolves it to DRAW, the same value a mutual wipe gives, so
## every run tool counts it as an ordinary loss and nothing anywhere says the
## fight never finished. That is the failure mode this constant is most able
## to hide, which is why the budget should not also move on its own.
const MAX_TICKS := 3600

## The party deploys inside the left-hand fraction of the arena, so a fight
## always begins with ground between the two sides and somebody has to cross it.
##
## The user's call, and it is a design rule rather than a layout preference:
## without it an encounter can be authored with the two sides already in contact,
## and then positioning, movement speed, kiting and the whole ranged-versus-melee
## distinction stop mattering on tick one. Traversal is what makes a Geysermancer
## different from a Warrior.
##
## Encounter authors keep every entry in `party_spawns` at or left of
## `party_deploy_max_x()`. Enemies are deliberately unconstrained: putting the
## dangerous ones deep is one of the levers issue 12 is about.
## The encounter every tool means when it says "a fight" without qualifying it.
##
## Named rather than picked by index, because picking by index is a bug waiting
## for a second encounter to exist. `Registry.all_encounter_ids()[0]` was correct
## while there was exactly one and became silently wrong the moment there were
## three — the list sorts alphabetically, so `floor1_ghoul_den` displaced
## `floor1_room1` and every tool that reached for [0] quietly changed subject.
##
## teal found that in Tools/SampleFights.gd. I then fixed that one file and left
## the same line in three other tools, which is the fix-the-instance mistake I
## had told teal not to make about plan ranges an hour earlier.
const DEFAULT_ENCOUNTER := &"floor1_room1"

const PARTY_DEPLOY_FRACTION := 1.0 / 3.0

## Rightmost x a party member may start at. Derived rather than typed so it
## cannot drift away from the arena bounds.
static func party_deploy_max_x() -> float:
	return -ARENA_HALF_WIDTH + (ARENA_HALF_WIDTH * 2.0 * PARTY_DEPLOY_FRACTION)

enum Team {
	PLAYER,
	ENEMY,
}

enum Attribute {
	STR,
	DEX,
	AGI,
	CON,
	INT,
	ATN,
	WIS,
}

enum ResourceKind {
	MANA,
	RAGE,
	ENERGY,
}

enum DamageType {
	PHYSICAL,
	FIRE,
	WATER,
	AIR,
	EARTH,
	DIVINE,
	PROFANE,
	RAW,
}

enum Method { MARTIAL, MAGICAL }
enum Style { MELEE, RANGED, SUMMONER }
enum Role { DPS, SUPPORT, ANTI_SUPPORT, TANK, HEALER }

## Status effects. Each damage type has one helpful and one harmful effect in
## README.md; only the ones the slice actually applies are listed. Adding one is
## a manager edit, not a content edit, because the sim must handle it.
enum Status {
	SHIELD,
	BLEED,
	ENRAGE,
	BURN,
	HASTE,
	STUN,
	BLOCK,
	MARKED,
	POISON,
	## Appended, never inserted. These values are written into CombatEvent.status
	## and read by the log and the floaters, so shifting an existing one would
	## silently relabel every status in a saved event stream.
	##
	## SLOWED scales a unit's movement, not its action timing. HASTE already
	## covers action timing (wind-up and recovery through deps.haste_tick_scale)
	## and deliberately does not touch movement; this is the other axis. Kept
	## separate rather than making one status do both, because a grapple that
	## also made a unit swing faster would be a strange grapple.
	##
	## Distinct from STUN, which is a full lockout -- a stunned unit neither
	## decides nor acts. A slow leaves a unit fighting, just unable to leave.
	SLOWED,
	## Enemies within a radius are forced to focus the taunting unit. This is
	## what makes TANK mean something: every class tagged TANK has high CON and
	## no way to make anything attack it, so "tank" has meant "survives" rather
	## than "protects". Nothing in this codebase redirects a target today.
	TAUNTING,
	## A ranged attack crossing this unit's front arc is stopped by it.
	##
	## How this resolves depends on a decision the player has since made: most
	## shots should be real projectiles that travel. Once they do, this is simply
	## a projectile hitting the Warrior instead of its target, which is both more
	## obvious to a player and more honest than a geometric test.
	##
	## Until projectiles exist it can be resolved as a line check at fire time,
	## the same way Terrain.line_is_blocked already stops a shot at a wall. That
	## is the fallback, not the design.
	SHIELDING,
	## This unit is holding a sustained action: an effect that ticks every tick
	## and charges it resource every tick, for as long as its plan keeps
	## choosing it. Issue 61.
	##
	## Appended, never inserted, same rule the rest of this enum carries.
	##
	## Not harmful, so a cleanse never strips a pawn's own channel.
	##
	## It exists so the *middle* of a channel is visible, not only its two ends.
	## SUSTAIN_START and SUSTAIN_END below mark the boundaries in the log; this
	## is what puts a badge on the unit for every tick in between. An effect that
	## ticks invisibly is the failure this project keeps repeating, and it is
	## what made the Warrior's block unevaluable for weeks.
	##
	## Carries a magnitude on the unit the way TAUNTING does: `CombatUnit.taunt_radius`
	## for that one, `CombatUnit.sustaining` (which action) for this one.
	SUSTAINING,
}

## Whether a status is something a unit would want removed. Cleanse needs this
## and nothing else does yet.
##
## Kept as a function rather than a second enum so there is one list rather than
## two that can disagree. A status added without being classified here is
## treated as harmless, which is the safe direction: a cleanse that misses
## something is a weaker cleanse, where a cleanse that strips SHIELD or HASTE
## would be actively hostile to the ally it targeted.
static func is_harmful(s: Status) -> bool:
	match s:
		Status.BLEED, Status.BURN, Status.POISON, Status.STUN, 		Status.MARKED, Status.SLOWED:
			return true
	return false

## What a decision layer asks a unit to do on a tick. The plan interpreter and
## the default behaviour both produce these; the simulation consumes them and is
## the only thing allowed to mutate a CombatUnit.
enum IntentKind {
	IDLE,
	MOVE_TO,
	USE_ACTION,
}

## Everything the simulation reports outwards. The view and the combat log read
## these and nothing else: no reaching into CombatUnit for "what just happened".
enum EventKind {
	FIGHT_START,
	FIGHT_END,
	DAMAGE,
	HEAL,
	DEATH,
	ACTION_START,
	ACTION_FIRE,
	STATUS_APPLIED,
	STATUS_EXPIRED,
	RESOURCE_SPENT,
	## An action landed and reached nothing: the target left range during the
	## wind-up, or was never in range when the action was committed.
	##
	## Added after reading a whole fight and finding a Geysermancer that fired
	## six times and connected once, with nothing anywhere saying why. On screen
	## and in the log it read as "my caster keeps casting and nothing happens",
	## which is indistinguishable from a broken game. A miss is a legitimate
	## outcome and it has to be legible as one.
	MISS,
	## A SHIELDING unit stepped in front of a hostile shot and took it instead
	## of whoever it was aimed at.
	##
	## Appended, never inserted, same rule Status already carries: these values
	## are written into CombatEvent.kind and read by the log and the floaters.
	##
	## `source_id` is the shooter and `action_id` is the shooter's action, so
	## the pair reads the same way it does on DAMAGE and MISS. `target_id` is
	## the unit that blocked -- not the unit the shot was aimed at, which is
	## already gone from the outcome by the time this fires. Same shape the
	## cleanse's STATUS_EXPIRED uses: the event names the actor whose
	## behaviour is otherwise invisible.
	##
	## Emitted immediately before the redirected hit resolves, so a log reads
	## "blocked" and then the damage the blocker took for it.
	##
	## Added because the interception wrote nothing at all: no log line, no
	## floater, and a probe (Tools/BlockProbe.gd) that could only count
	## opportunities. An ability whose entire effect is invisible cannot be
	## evaluated by a player or by us, and this one was not, for weeks.
	BLOCKED,
	## A unit began holding a sustained action. Issue 61.
	##
	## Appended, never inserted, same rule as BLOCKED above.
	##
	## `source_id` is the caster, `action_id` is the action, `target_id` is -1 --
	## a channel is aimed at an area around its caster rather than at a unit.
	## Emitted from `_fire_action`, immediately after ACTION_FIRE, so the pair
	## reads "the Abomination ignites" and then "and is now burning".
	SUSTAIN_START,
	## A unit stopped holding a sustained action, whatever ended it: its plan
	## chose something else, its resource ran out, it was stunned, or it died.
	##
	## `amount` is how many ticks it was held for. That number is not recoverable
	## from the event stream otherwise, and it is the one thing a player wants to
	## know about a channel after it is over.
	##
	## **The end *reason* is deliberately not encoded**, and that is a decision
	## rather than an oversight -- it would want another field on CombatEvent, and
	## whether a player needs to tell "I ran out of rage" from "my plan switched"
	## apart is a question about the plan editor, not about the simulation. Say
	## the word and it is one more field.
	SUSTAIN_END,
}

static func attribute_name(a: Attribute) -> String:
	match a:
		Attribute.STR: return "STR"
		Attribute.DEX: return "DEX"
		Attribute.AGI: return "AGI"
		Attribute.CON: return "CON"
		Attribute.INT: return "INT"
		Attribute.ATN: return "ATN"
		Attribute.WIS: return "WIS"
	return "?"

static func damage_type_name(d: DamageType) -> String:
	match d:
		DamageType.PHYSICAL: return "Physical"
		DamageType.FIRE: return "Fire"
		DamageType.WATER: return "Water"
		DamageType.AIR: return "Air"
		DamageType.EARTH: return "Earth"
		DamageType.DIVINE: return "Divine"
		DamageType.PROFANE: return "Profane"
		DamageType.RAW: return "Raw"
	return "?"
